### ISSUE TITLE
Error when rebuilding the discourse app

### ISSUE THREAD

**Issue by mercadocapote** [santiment/discourse-ethereum#16]
I get the following error when i add this discourse plugin and the app fails to rebuild.
If i dont include the plugin app rebuilds fine.

![capture](https://user-images.githubusercontent.com/23019072/48144251-eb8a3b00-e286-11e8-8633-536bfd066862.PNG)

**Comment by tzanko-matev** [comment]
The error was due to a bug introduced with the lates commit. It should be fixed now
