### ISSUE TITLE
Error compiling with Discourse.

### ISSUE THREAD

**Issue by b4sh1t1** [santiment/discourse-ethereum#20]
Hello,

I'm trying to use this plugin; and my discourse get this error while rebuilding the discourse;

`precompile target: discourse-ethereum
rake aborted!
Discourse::ScssError: Error: Invalid CSS after "  }": expected selector, was ","
        on line 68 of discourse-ethereum.scss
>>   },

   ---^
/var/www/discourse/lib/stylesheet/manager/builder.rb:52:in `rescue in block in compile'
/var/www/discourse/lib/stylesheet/manager/builder.rb:34:in `block in compile'
/var/www/discourse/lib/stylesheet/manager/builder.rb:165:in `with_load_paths'
/var/www/discourse/lib/stylesheet/manager/builder.rb:33:in `compile'
/var/www/discourse/lib/stylesheet/manager.rb:51:in `block in precompile_css'
/var/www/discourse/lib/stylesheet/manager.rb:48:in `each'
/var/www/discourse/lib/stylesheet/manager.rb:48:in `precompile_css'
/var/www/discourse/lib/tasks/assets.rake:59:in `block (2 levels) in <main>'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/rails_multisite-4.0.0/lib/rails_multisite/connection_management.rb:80:in `with_connection'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/rails_multisite-4.0.0/lib/rails_multisite/connection_management.rb:90:in `each_connection'
/var/www/discourse/lib/tasks/assets.rake:53:in `block in <main>'
/var/www/discourse/lib/tasks/assets.rake:430:in `block in <main>'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'

Caused by:
SassC::SyntaxError: Error: Invalid CSS after "  }": expected selector, was ","
        on line 68 of discourse-ethereum.scss
>>   },

   ---^
discourse-ethereum.scss:68
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/sassc-2.0.1/lib/sassc/engine.rb:49:in `render'
`

Any suggestion ?

**Comment by chicodias** [comment]
This issue can be fixed, at 

https://github.com/santiment/discourse-ethereum/blob/06047d1922b76cbc9062e7116f0415aa4c7a608c/assets/stylesheets/common.scss#L68

just remove the comma

**Comment by tspenov** [comment]
fixed in https://github.com/santiment/discourse-ethereum/pull/17
