### ISSUE TITLE
Send ETH UI hangs after Metamask completes the transaction on Kovan test network

### ISSUE THREAD

**Issue by tzanko-matev** [santiment/discourse-ethereum#3]
After I sucessfully send ETH on Kovan via metamask the Discourse UI hangs. The console shows the following error message:
```
Uncaught TypeError: Cannot read property 'hash' of null
```
The error appears at the following line:
https://github.com/santiment/discourse-ethereum/blob/97256031228aeeba0bf15c03a0a5728a259e58fa/assets/javascripts/discourse/controllers/send-eth.js.es6#L160

Apparently `web3.eth.getTransaction` returns null when the transaction is still pending. This is a known bug: https://github.com/ethereum/web3.js/issues/1679

**Comment by tzanko-matev** [comment]
I'm still getting the same issue, here is the guilty line of code:

https://github.com/santiment/discourse-ethereum/blob/c31ae1474f9a5561fa360ea23863451e876d5391/assets/javascripts/discourse/controllers/send-eth.js.es6#L196

**Comment by joebuhlig** [comment]
Got it. We’ll take a look. I thought we had this one.

**Comment by joebuhlig** [comment]
Should have this one resolved. https://github.com/santiment/discourse-ethereum/pull/14/commits/49ec878d735f64b48e246124e39efb363a94606b
